name: illumina2lineage
channels:
  - conda-forge
  - bioconda
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - annotated-types
  - click
  - dendropy
  - bedtools
  - pyyaml
  - docutils
  - freebayes
  - bcftools=1.17
  - pillow
  - wheel
  - k8
  - samtools
  - tqdm
  - python=3.12
  - bamclipper
  - appdirs
  - jinja2
  - requests
  - amply
  - vcftools
  - screed
  - idna
  - pandas
  - gsl
  - setuptools
  - tabulate
  - plotly
  - multiqc
  - htslib
  - pip
  - argparse-dataclass
  - regex
  - iqtree
  - mafft
  - aria2
  - igv
  - zlib
  - biopython
  - minimap2
  - pulp
  - configargparse
  - fastqc
  - president
  - fastp
  - attrs
  - rich
  - six
  - pigz
  - graphviz
