name: sars_genome_assembly
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - amply
  - annotated-types
  - appdirs
  - argparse-dataclass
  - aria2
  - attrs
  - bamclipper
  - bcftools
  - bedtools
  - biopython
  - click
  - configargparse
  - dendropy
  - docutils
  - fastp
  - fastqc
  - freebayes
  - gsl
  - htslib
  - idna
  - igv
  - iqtree
  - jinja2
  - k8
  - mafft
  - minimap2
  - multiqc
  - pandas
  - pillow
  - pip
  - plotly
  - president
  - pulp
  - pyyaml
  - python=3.12
  - regex
  - requests
  - rich
  - samtools
  - screed
  - setuptools
  - six
  - snakemake-minimal
  - tabulate
  - tqdm
  - vcftools
  - wheel
  - zlib